// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbsvfcgpwekqwmebhzcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRic3ZmY2dwd2VrcXdtZWJoemN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MDc5ODYsImV4cCI6MjA4ODM4Mzk4Nn0.62aqhEsjdSHVo-VrpqssFalpGwrxdC0j_dZQHfkUhBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});